### ISSUE TITLE
Building and using user defined PDFs

### ISSUE THREAD

**Issue by jamesgrogers** [pgromano/pinky#1]
How do I build pinky on my machine? Also how does one sample from user defined PDFs?

**Comment by pgromano** [comment]
I'll start with a huge warning: This was something I wrote in grad school for a one off analysis and basically haven't supported since. Pinky is *only* intended to sample from 2D discrete distributions. In other words, histograms from empirical observations. If you know the analytical distribution you could sample from methods like [inverse transform sampling](https://en.wikipedia.org/wiki/Inverse_transform_sampling). Otherwise, you can compute the PDF on a predefined space and pass that in 

```python
x = np.linspace(0, 1, 100)
y = np.linspace(0, 1, 100)
XX, YY = np.meshgrid(x, y)

# not sure if this how your custom pdf works
P = custom_pdf(XX, YY) 

# initialize pinky
sampler = Pinky(P=P)
```

Sorry can you be more specific? Do you mean installing pinky? 

```bash
# if you're using conda
conda activate <NAME OF YOUR CONDA ENV>

# clone
git clone https://github.com/pgromano/pinky.git
cd pinky

# install
pip install -e .
```

**Comment by jamesgrogers** [comment]
Perfect thank you very much - this is all the information I needed.
